# Generated by Django 4.2.6 on 2023-11-30 22:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_alter_projects_options_alter_skills_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='skill_img',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
