# Generated by Django 5.2.1 on 2025-12-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_alter_skills_skill_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='kaggle_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='live_link',
            field=models.URLField(blank=True),
        ),
    ]
