# Generated by Django 5.2.1 on 2026-02-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_projects_kaggle_link_alter_projects_live_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='kaggle_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
